# Generated by Django 5.1.5 on 2025-01-27 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GymClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, unique=True)),
                ('body', models.TextField()),
                ('image', models.ImageField(upload_to='images/classes')),
            ],
            options={
                'verbose_name': 'Gym Class',
                'verbose_name_plural': 'Gym Classes',
            },
        ),
    ]
